"""initial schema

Revision ID: 21db927b19fb
Revises: 
Create Date: 2026-02-11 06:10:30.071499
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision: str = '21db927b19fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asins',
    sa.Column('asin', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('category_path', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('bsr_rank', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('bullet_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('date_first_available', sa.Date(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('asin')
    )
    op.create_index(op.f('ix_asins_brand'), 'asins', ['brand'], unique=False)
    op.create_table('error_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('context_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dag_id', sa.String(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('records_fetched', sa.Integer(), nullable=True),
    sa.Column('records_inserted', sa.Integer(), nullable=True),
    sa.Column('records_skipped', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('running', 'success', 'failed', 'partial')", name='ck_runs_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orgs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("plan IN ('free', 'pro', 'enterprise')", name='ck_orgs_plan'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('primary_category', sa.String(), nullable=True),
    sa.Column('embedding', Vector(384), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("stage IN ('emerging', 'exploding', 'peaking', 'declining', 'unknown')", name='ck_topics_stage'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_primary_category'), 'topics', ['primary_category'], unique=False)
    op.create_index(op.f('ix_topics_slug'), 'topics', ['slug'], unique=True)
    op.create_table('amazon_competition_snapshot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('marketplace', sa.String(), nullable=True),
    sa.Column('listing_count', sa.Integer(), nullable=True),
    sa.Column('median_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('avg_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_std', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('median_reviews', sa.Integer(), nullable=True),
    sa.Column('avg_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('brand_count', sa.Integer(), nullable=True),
    sa.Column('brand_hhi', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('top3_brand_share', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('rating_distribution_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('price_range_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'date', 'marketplace', name='uq_competition_unique')
    )
    op.create_table('derived_features',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('feature_name', sa.String(), nullable=False),
    sa.Column('feature_value', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'date', 'feature_name', name='uq_features_unique')
    )
    op.create_table('dq_metrics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('metric_value', sa.Numeric(), nullable=True),
    sa.Column('threshold', sa.Numeric(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('horizon_months', sa.Integer(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('yhat', sa.Numeric(), nullable=True),
    sa.Column('yhat_lower', sa.Numeric(), nullable=True),
    sa.Column('yhat_upper', sa.Numeric(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('horizon_months IN (3, 6)', name='ck_forecasts_horizon'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_forecasts_topic', 'forecasts', ['topic_id', 'generated_at'], unique=False)
    op.create_table('gen_next_specs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('must_fix_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('must_add_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('differentiators_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('positioning_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gennext_topic', 'gen_next_specs', ['topic_id', 'generated_at'], unique=False)
    op.create_table('keywords',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('geo', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('latest_volume', sa.BigInteger(), nullable=True),
    sa.Column('latest_cpc', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("source IN ('keywordtool', 'junglescout', 'gtrends', 'reddit')", name='ck_keywords_source'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword', 'source', 'geo', name='uq_keywords_unique')
    )
    op.create_index('idx_keywords_topic', 'keywords', ['topic_id'], unique=False)
    op.create_table('reviews',
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('asin', sa.String(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('verified_purchase', sa.Boolean(), nullable=True),
    sa.Column('helpful_votes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('stars BETWEEN 1 AND 5', name='ck_reviews_stars'),
    sa.ForeignKeyConstraint(['asin'], ['asins.asin'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index('idx_reviews_date', 'reviews', ['review_date'], unique=False)
    op.create_index(op.f('ix_reviews_asin'), 'reviews', ['asin'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('score_type', sa.String(), nullable=False),
    sa.Column('score_value', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('explanation_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("score_type IN ('opportunity', 'competition', 'demand', 'review_gap')", name='ck_scores_type'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scores_latest', 'scores', ['topic_id', 'score_type', 'computed_at'], unique=False)
    op.create_table('source_timeseries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('geo', sa.String(), nullable=True),
    sa.Column('raw_value', sa.Numeric(), nullable=True),
    sa.Column('normalized_value', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'source', 'date', 'geo', name='uq_ts_unique')
    )
    op.create_index('idx_ts_topic_date', 'source_timeseries', ['topic_id', 'date'], unique=False)
    op.create_table('topic_category_map',
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_id', 'category')
    )
    op.create_table('topic_top_asins',
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('asin', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('relevance_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asin'], ['asins.asin'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('topic_id', 'asin')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('viewer', 'editor', 'admin')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_org', 'users', ['org_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("alert_type IN ('stage_change', 'score_threshold', 'new_competitor', 'price_drop')", name='ck_alerts_type'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_aspects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('aspect', sa.String(), nullable=False),
    sa.Column('sentiment', sa.String(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('evidence_snippet', sa.Text(), nullable=True),
    sa.CheckConstraint("sentiment IN ('positive', 'negative', 'neutral')", name='ck_aspects_sentiment'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.review_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_aspects_aspect', 'review_aspects', ['aspect', 'sentiment'], unique=False)
    op.create_index(op.f('ix_review_aspects_review_id'), 'review_aspects', ['review_id'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id', name='uq_watchlist_user_topic')
    )
    op.create_table('alert_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_events')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_review_aspects_review_id'), table_name='review_aspects')
    op.drop_index('idx_aspects_aspect', table_name='review_aspects')
    op.drop_table('review_aspects')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_org', table_name='users')
    op.drop_table('users')
    op.drop_table('topic_top_asins')
    op.drop_table('topic_category_map')
    op.drop_index('idx_ts_topic_date', table_name='source_timeseries')
    op.drop_table('source_timeseries')
    op.drop_index('idx_scores_latest', table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_reviews_asin'), table_name='reviews')
    op.drop_index('idx_reviews_date', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('idx_keywords_topic', table_name='keywords')
    op.drop_table('keywords')
    op.drop_index('idx_gennext_topic', table_name='gen_next_specs')
    op.drop_table('gen_next_specs')
    op.drop_index('idx_forecasts_topic', table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_table('dq_metrics')
    op.drop_table('derived_features')
    op.drop_table('amazon_competition_snapshot')
    op.drop_index(op.f('ix_topics_slug'), table_name='topics')
    op.drop_index(op.f('ix_topics_primary_category'), table_name='topics')
    op.drop_table('topics')
    op.drop_table('orgs')
    op.drop_table('ingestion_runs')
    op.drop_table('error_logs')
    op.drop_index(op.f('ix_asins_brand'), table_name='asins')
    op.drop_table('asins')
    # ### end Alembic commands ###
