import { useState, useEffect, useMemo } from 'react';

/* ═══ Palette (warm NeuraNest) ═══ */
const C = {
  bg: '#F9F7F4', card: '#FFFFFF', border: '#E6E1DA', borderLight: '#F0ECE6',
  coral: '#E8714A', coralLight: '#FCEEE8', coralDark: '#C25A36',
  sage: '#1A8754', sageLight: '#E8F5EE',
  amber: '#D4930D', amberLight: '#FFF8E6',
  rose: '#C0392B', roseLight: '#FFF0F0',
  plum: '#7C3AED', plumLight: '#F3EEFF',
  charcoal: '#2D3E50', charcoalDeep: '#1A2A3A',
  ink: '#2A2520', slate: '#5C5549', stone: '#8B8479', sand: '#B8B2A8',
};

const API_BASE = 'http://localhost:8000/api/v1';

/* ═══ Embedded backtest data (generated by backtest_engine.py) ═══ */
/* This will be loaded from the API or from a static JSON file */

interface MonthlyScore {
  month: string;
  total: number;
  search_momentum: number;
  social_buzz: number;
  demand_rank: number;
  category_base: number;
  trend_direction: number;
  data_richness: number;
  gt_value: number;
  ba_rank: number | null;
  reddit_posts: number;
}

interface BacktestResult {
  name: string;
  category: string;
  known_peak: string;
  narrative: string;
  peak_score: number;
  peak_month: string | null;
  detection_date: string | null;
  exploding_date: string | null;
  lead_time_months: number | null;
  monthly_scores: MonthlyScore[];
  data_coverage: {
    google_trends_months: number;
    amazon_ba_months: number;
    reddit_months: number;
  };
}

/* ═══ Mini Chart Components ═══ */
function TrajectoryChart({ data, width = 720, height = 220 }: {
  data: MonthlyScore[]; width?: number; height?: number;
}) {
  if (!data || data.length < 2) return null;
  const pad = { top: 20, right: 20, bottom: 36, left: 44 };
  const w = width - pad.left - pad.right;
  const h = height - pad.top - pad.bottom;
  const maxScore = Math.max(...data.map(d => d.total), 100);

  const points = data.map((d, i) => ({
    x: pad.left + (i / (data.length - 1)) * w,
    y: pad.top + h - (d.total / maxScore) * h,
    score: d.total,
    month: d.month,
  }));

  const line = points.map((p, i) => `${i === 0 ? 'M' : 'L'}${p.x},${p.y}`).join(' ');
  const area = `${line} L${points[points.length - 1].x},${pad.top + h} L${points[0].x},${pad.top + h} Z`;

  // Threshold lines
  const y40 = pad.top + h - (40 / maxScore) * h;
  const y60 = pad.top + h - (60 / maxScore) * h;

  // Month labels (every 3rd)
  const monthLabels = data.filter((_, i) => i % 3 === 0).map((d, i) => {
    const idx = data.indexOf(d);
    return {
      x: pad.left + (idx / (data.length - 1)) * w,
      label: d.month.slice(0, 7),
    };
  });

  return (
    <svg width={width} height={height} viewBox={`0 0 ${width} ${height}`} style={{ display: 'block' }}>
      <defs>
        <linearGradient id="traj-grad" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stopColor={C.coral} stopOpacity="0.25" />
          <stop offset="100%" stopColor={C.coral} stopOpacity="0.02" />
        </linearGradient>
        <linearGradient id="traj-line-grad" x1="0" y1="0" x2="1" y2="0">
          <stop offset="0%" stopColor={C.sage} />
          <stop offset="50%" stopColor={C.coral} />
          <stop offset="100%" stopColor={C.coralDark} />
        </linearGradient>
      </defs>

      {/* Grid lines */}
      {[0, 20, 40, 60, 80, 100].map(v => {
        const y = pad.top + h - (v / maxScore) * h;
        return (
          <g key={v}>
            <line x1={pad.left} y1={y} x2={pad.left + w} y2={y}
              stroke={C.borderLight} strokeWidth={v === 40 || v === 60 ? 1.5 : 0.5}
              strokeDasharray={v === 40 || v === 60 ? '6,4' : 'none'} />
            <text x={pad.left - 8} y={y + 4} textAnchor="end" fill={C.stone}
              fontSize="10" fontFamily="'JetBrains Mono', monospace">{v}</text>
          </g>
        );
      })}

      {/* Threshold zones */}
      <rect x={pad.left} y={y60} width={w} height={y40 - y60}
        fill={C.amberLight} opacity={0.3} />
      <rect x={pad.left} y={pad.top} width={w} height={y60 - pad.top}
        fill={C.coralLight} opacity={0.25} />

      {/* Threshold labels */}
      <text x={pad.left + w + 4} y={y40 + 3} fill={C.sage} fontSize="9" fontWeight="600">EMERGING</text>
      <text x={pad.left + w + 4} y={y60 + 3} fill={C.coral} fontSize="9" fontWeight="600">EXPLODING</text>

      {/* Area fill */}
      <path d={area} fill="url(#traj-grad)" />

      {/* Line */}
      <path d={line} fill="none" stroke="url(#traj-line-grad)" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />

      {/* Data points */}
      {points.map((p, i) => (
        <circle key={i} cx={p.x} cy={p.y} r={p.score >= 60 ? 4 : 3}
          fill={p.score >= 60 ? C.coral : p.score >= 40 ? C.sage : C.stone}
          stroke={C.card} strokeWidth="1.5" />
      ))}

      {/* Month labels */}
      {monthLabels.map((m, i) => (
        <text key={i} x={m.x} y={pad.top + h + 20} textAnchor="middle"
          fill={C.stone} fontSize="9" fontFamily="'JetBrains Mono', monospace"
          transform={`rotate(-30, ${m.x}, ${pad.top + h + 20})`}>{m.label}</text>
      ))}
    </svg>
  );
}

function SignalBars({ data }: { data: MonthlyScore[] }) {
  if (!data || data.length < 2) return null;
  const barW = Math.max(4, Math.floor(600 / data.length) - 2);

  return (
    <div style={{ display: 'flex', gap: 2, alignItems: 'flex-end', height: 60, padding: '0 4px' }}>
      {data.map((d, i) => {
        const gtH = Math.max(1, (d.gt_value / 100) * 50);
        const rdH = Math.max(0, Math.min(50, d.reddit_posts * 3));
        const baH = d.ba_rank ? Math.max(1, Math.min(50, (1 - Math.min(d.ba_rank, 1000) / 1000) * 50)) : 0;
        return (
          <div key={i} style={{ display: 'flex', flexDirection: 'column', gap: 1, width: barW }}>
            <div style={{ height: gtH, background: C.plum, borderRadius: 1, opacity: 0.7 }} title={`GT: ${d.gt_value}`} />
            <div style={{ height: rdH, background: C.sage, borderRadius: 1, opacity: 0.7 }} title={`Reddit: ${d.reddit_posts}`} />
            <div style={{ height: baH, background: C.coral, borderRadius: 1, opacity: 0.7 }} title={`BA: ${d.ba_rank}`} />
          </div>
        );
      })}
    </div>
  );
}

function MetricPill({ label, value, color, sub }: { label: string; value: string | number; color: string; sub?: string }) {
  return (
    <div style={{
      padding: '12px 16px', borderRadius: 12, background: color + '12',
      border: `1px solid ${color}22`, minWidth: 120, textAlign: 'center',
    }}>
      <div style={{ fontSize: 10, color: C.stone, fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 4 }}>{label}</div>
      <div style={{ fontSize: 22, fontWeight: 700, color, fontFamily: "'JetBrains Mono', monospace" }}>{value}</div>
      {sub && <div style={{ fontSize: 10, color: C.sand, marginTop: 2 }}>{sub}</div>}
    </div>
  );
}

/* ═══ Main Page ═══ */
export default function BacktestPage() {
  const [results, setResults] = useState<BacktestResult[]>([]);
  const [selected, setSelected] = useState<number>(0);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Try to load from API first, fall back to static data
    fetch('/backtest_report.json')
      .then(r => r.ok ? r.json() : null)
      .then(data => {
        if (data?.results) {
          setResults(data.results);
        } else {
          // Fallback: load from API endpoint
          const token = localStorage.getItem('access_token') || '';
          fetch(`${API_BASE}/backtest/results`, {
            headers: token ? { Authorization: `Bearer ${token}` } : {},
          })
            .then(r => r.ok ? r.json() : null)
            .then(apiData => {
              if (apiData?.results) setResults(apiData.results);
            })
            .catch(() => {});
        }
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, []);

  const current = results[selected];

  const summaryStats = useMemo(() => {
    if (!results.length) return null;
    const detected = results.filter(r => r.detection_date).length;
    const exploded = results.filter(r => r.exploding_date).length;
    const leads = results.filter(r => r.lead_time_months).map(r => r.lead_time_months!);
    const avgLead = leads.length > 0 ? leads.reduce((a, b) => a + b, 0) / leads.length : 0;
    const avgPeak = results.reduce((a, r) => a + r.peak_score, 0) / results.length;
    return { detected, exploded, avgLead, avgPeak, total: results.length };
  }, [results]);

  if (loading) {
    return (
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100vh', background: C.bg }}>
        <div style={{ textAlign: 'center' }}>
          <div style={{ fontSize: 32, marginBottom: 12 }}>📊</div>
          <div style={{ color: C.coral, fontSize: 16 }}>Loading backtest results...</div>
        </div>
      </div>
    );
  }

  if (!results.length) {
    return (
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100vh', background: C.bg }}>
        <div style={{
          textAlign: 'center', background: C.card, padding: '48px 64px', borderRadius: 20,
          border: `1px solid ${C.border}`, maxWidth: 500,
        }}>
          <div style={{ fontSize: 48, marginBottom: 16 }}>🔬</div>
          <h2 style={{ fontSize: 22, fontWeight: 400, color: C.charcoalDeep, fontFamily: "'Newsreader', Georgia, serif", margin: '0 0 12px' }}>
            No Backtest Data Yet
          </h2>
          <p style={{ color: C.stone, fontSize: 14, lineHeight: 1.6, margin: 0 }}>
            Run the backtesting engine to generate prediction accuracy data.
            Place <code style={{ background: C.borderLight, padding: '2px 6px', borderRadius: 4, fontSize: 12 }}>backtest_report.json</code> in
            the frontend public folder to visualize results here.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div style={{
      minHeight: '100vh', background: C.bg, color: C.ink,
      fontFamily: "'Plus Jakarta Sans', -apple-system, sans-serif",
      padding: '28px 36px',
    }}>
      {/* ═══ Header ═══ */}
      <div style={{ marginBottom: 24 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 6 }}>
          <span style={{ fontSize: 24 }}>🔬</span>
          <h1 style={{
            fontSize: 28, fontWeight: 400, margin: 0, letterSpacing: '-0.02em',
            color: C.charcoalDeep, fontFamily: "'Newsreader', Georgia, serif",
          }}>
            Prediction Accuracy
          </h1>
          <span style={{
            padding: '4px 12px', borderRadius: 20, fontSize: 11, fontWeight: 600,
            background: C.sageLight, color: C.sage,
          }}>BACKTESTED</span>
        </div>
        <p style={{ color: C.stone, fontSize: 13, margin: 0 }}>
          Simulated monthly scoring over 24 months (Feb 2024 → Jan 2026) using historical data. No future leakage.
        </p>
      </div>

      {/* ═══ Summary KPIs ═══ */}
      {summaryStats && (
        <div style={{ display: 'flex', gap: 14, marginBottom: 24, flexWrap: 'wrap' }}>
          <MetricPill label="Detection Rate" value={`${summaryStats.detected}/${summaryStats.total}`}
            color={C.sage} sub={`${((summaryStats.detected / summaryStats.total) * 100).toFixed(0)}% hit rate`} />
          <MetricPill label="Exploding Rate" value={`${summaryStats.exploded}/${summaryStats.total}`}
            color={C.coral} sub={`${((summaryStats.exploded / summaryStats.total) * 100).toFixed(0)}% caught early`} />
          <MetricPill label="Avg Lead Time" value={`${summaryStats.avgLead.toFixed(1)}mo`}
            color={C.plum} sub="before peak" />
          <MetricPill label="Avg Peak Score" value={summaryStats.avgPeak.toFixed(1)}
            color={C.amber} sub="out of 100" />
          <MetricPill label="Products Tested" value={summaryStats.total}
            color={C.charcoal} sub="across categories" />
        </div>
      )}

      {/* ═══ Product Selector ═══ */}
      <div style={{
        display: 'flex', gap: 8, marginBottom: 20, overflowX: 'auto',
        padding: '4px 0',
      }}>
        {results.map((r, i) => {
          const active = i === selected;
          const hasExploded = !!r.exploding_date;
          return (
            <button key={i} onClick={() => setSelected(i)} style={{
              padding: '10px 18px', borderRadius: 12, border: `1.5px solid ${active ? C.coral : C.border}`,
              background: active ? C.coralLight : C.card, cursor: 'pointer',
              transition: 'all 0.2s', whiteSpace: 'nowrap', minWidth: 'fit-content',
            }}>
              <div style={{ fontSize: 13, fontWeight: 600, color: active ? C.coral : C.ink }}>
                {hasExploded ? '🔥' : '🌱'} {r.name}
              </div>
              <div style={{ fontSize: 10, color: active ? C.coralDark : C.sand, marginTop: 2 }}>
                {r.category} · Peak: {r.peak_score.toFixed(0)}
              </div>
            </button>
          );
        })}
      </div>

      {current && (
        <>
          {/* ═══ Selected Product Header ═══ */}
          <div style={{
            background: C.card, borderRadius: 16, padding: '24px 28px', marginBottom: 16,
            border: `1px solid ${C.border}`, boxShadow: '0 2px 8px rgba(42,37,32,0.06)',
          }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
              <div>
                <h2 style={{
                  fontSize: 24, fontWeight: 400, margin: '0 0 6px',
                  color: C.charcoalDeep, fontFamily: "'Newsreader', Georgia, serif",
                }}>
                  {current.name}
                </h2>
                <div style={{ display: 'flex', gap: 12, alignItems: 'center' }}>
                  <span style={{
                    padding: '3px 10px', borderRadius: 20, fontSize: 11, fontWeight: 600,
                    background: C.plumLight, color: C.plum,
                  }}>{current.category}</span>
                  <span style={{ fontSize: 12, color: C.stone }}>Known peak: {current.known_peak}</span>
                </div>
                <p style={{ fontSize: 13, color: C.slate, marginTop: 10, maxWidth: 600, lineHeight: 1.5 }}>
                  {current.narrative}
                </p>
              </div>

              <div style={{ display: 'flex', gap: 12 }}>
                <div style={{ textAlign: 'center' }}>
                  <div style={{ fontSize: 10, color: C.stone, fontWeight: 600, textTransform: 'uppercase', marginBottom: 4 }}>Peak Score</div>
                  <div style={{
                    width: 64, height: 64, borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center',
                    background: current.peak_score >= 60 ? C.coralLight : C.sageLight,
                    border: `3px solid ${current.peak_score >= 60 ? C.coral : C.sage}`,
                  }}>
                    <span style={{
                      fontSize: 20, fontWeight: 700, fontFamily: "'JetBrains Mono', monospace",
                      color: current.peak_score >= 60 ? C.coral : C.sage,
                    }}>{current.peak_score.toFixed(0)}</span>
                  </div>
                </div>
                <div style={{ textAlign: 'center' }}>
                  <div style={{ fontSize: 10, color: C.stone, fontWeight: 600, textTransform: 'uppercase', marginBottom: 4 }}>Lead Time</div>
                  <div style={{
                    width: 64, height: 64, borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center',
                    background: C.plumLight, border: `3px solid ${C.plum}`,
                  }}>
                    <span style={{ fontSize: 18, fontWeight: 700, fontFamily: "'JetBrains Mono', monospace", color: C.plum }}>
                      {current.lead_time_months ? `${current.lead_time_months}m` : '—'}
                    </span>
                  </div>
                </div>
              </div>
            </div>

            {/* Detection Timeline */}
            <div style={{
              display: 'flex', gap: 24, marginTop: 18, padding: '14px 18px',
              background: C.bg, borderRadius: 10,
            }}>
              <div>
                <span style={{ fontSize: 10, color: C.stone, fontWeight: 600 }}>FIRST DETECTED (≥40)</span>
                <div style={{ fontSize: 14, fontWeight: 700, color: C.sage, fontFamily: "'JetBrains Mono', monospace", marginTop: 2 }}>
                  {current.detection_date || 'Never'}
                </div>
              </div>
              <div style={{ width: 1, background: C.border }} />
              <div>
                <span style={{ fontSize: 10, color: C.stone, fontWeight: 600 }}>FIRST EXPLODING (≥60)</span>
                <div style={{ fontSize: 14, fontWeight: 700, color: current.exploding_date ? C.coral : C.sand, fontFamily: "'JetBrains Mono', monospace", marginTop: 2 }}>
                  {current.exploding_date || 'Never reached'}
                </div>
              </div>
              <div style={{ width: 1, background: C.border }} />
              <div>
                <span style={{ fontSize: 10, color: C.stone, fontWeight: 600 }}>PEAK MONTH</span>
                <div style={{ fontSize: 14, fontWeight: 700, color: C.charcoalDeep, fontFamily: "'JetBrains Mono', monospace", marginTop: 2 }}>
                  {current.peak_month || '—'}
                </div>
              </div>
              <div style={{ width: 1, background: C.border }} />
              <div>
                <span style={{ fontSize: 10, color: C.stone, fontWeight: 600 }}>DATA SOURCES</span>
                <div style={{ display: 'flex', gap: 6, marginTop: 4 }}>
                  <span style={{ padding: '2px 8px', borderRadius: 6, fontSize: 10, fontWeight: 600, background: current.data_coverage.google_trends_months > 0 ? C.plumLight : C.borderLight, color: current.data_coverage.google_trends_months > 0 ? C.plum : C.sand }}>
                    GT: {current.data_coverage.google_trends_months}mo
                  </span>
                  <span style={{ padding: '2px 8px', borderRadius: 6, fontSize: 10, fontWeight: 600, background: current.data_coverage.amazon_ba_months > 0 ? C.coralLight : C.borderLight, color: current.data_coverage.amazon_ba_months > 0 ? C.coral : C.sand }}>
                    BA: {current.data_coverage.amazon_ba_months}mo
                  </span>
                  <span style={{ padding: '2px 8px', borderRadius: 6, fontSize: 10, fontWeight: 600, background: current.data_coverage.reddit_months > 0 ? C.sageLight : C.borderLight, color: current.data_coverage.reddit_months > 0 ? C.sage : C.sand }}>
                    Reddit: {current.data_coverage.reddit_months}mo
                  </span>
                </div>
              </div>
            </div>
          </div>

          {/* ═══ Score Trajectory Chart ═══ */}
          <div style={{
            background: C.card, borderRadius: 16, padding: '22px 24px', marginBottom: 16,
            border: `1px solid ${C.border}`,
          }}>
            <h3 style={{ fontSize: 15, fontWeight: 600, margin: '0 0 4px', color: C.charcoalDeep }}>
              Score Trajectory
            </h3>
            <p style={{ fontSize: 11, color: C.sand, margin: '0 0 14px' }}>
              Monthly opportunity score using only data available at each point (no future leakage)
            </p>
            <TrajectoryChart data={current.monthly_scores} width={760} height={240} />
          </div>

          {/* ═══ Signal Layers + Monthly Table ═══ */}
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>

            {/* Signal Activation */}
            <div style={{
              background: C.card, borderRadius: 16, padding: '22px 24px',
              border: `1px solid ${C.border}`,
            }}>
              <h3 style={{ fontSize: 15, fontWeight: 600, margin: '0 0 4px', color: C.charcoalDeep }}>
                Signal Layer Activation
              </h3>
              <p style={{ fontSize: 11, color: C.sand, margin: '0 0 14px' }}>
                <span style={{ color: C.plum }}>■</span> Google Trends &nbsp;
                <span style={{ color: C.sage }}>■</span> Reddit &nbsp;
                <span style={{ color: C.coral }}>■</span> Amazon BA Rank
              </p>
              <SignalBars data={current.monthly_scores} />

              {/* Score Components Breakdown */}
              <div style={{ marginTop: 20 }}>
                <h4 style={{ fontSize: 13, fontWeight: 600, margin: '0 0 10px', color: C.charcoalDeep }}>
                  Score Components (Latest Month)
                </h4>
                {(() => {
                  const last = current.monthly_scores[current.monthly_scores.length - 1];
                  if (!last) return null;
                  const components = [
                    { label: 'Search Momentum', value: last.search_momentum, max: 25, color: C.plum },
                    { label: 'Social Buzz', value: last.social_buzz, max: 20, color: C.sage },
                    { label: 'Demand Rank', value: last.demand_rank, max: 20, color: C.coral },
                    { label: 'Category Base', value: last.category_base, max: 15, color: C.amber },
                    { label: 'Trend Direction', value: last.trend_direction, max: 10, color: C.charcoal },
                    { label: 'Data Richness', value: last.data_richness, max: 10, color: C.stone },
                  ];
                  return components.map((c, i) => (
                    <div key={i} style={{ marginBottom: 8 }}>
                      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 3 }}>
                        <span style={{ fontSize: 11, color: C.slate }}>{c.label}</span>
                        <span style={{ fontSize: 11, fontWeight: 700, color: c.color, fontFamily: "'JetBrains Mono', monospace" }}>
                          {c.value.toFixed(1)} / {c.max}
                        </span>
                      </div>
                      <div style={{ height: 5, background: C.borderLight, borderRadius: 3, overflow: 'hidden' }}>
                        <div style={{ height: '100%', width: `${(c.value / c.max) * 100}%`, background: c.color, borderRadius: 3, opacity: 0.8 }} />
                      </div>
                    </div>
                  ));
                })()}
              </div>
            </div>

            {/* Monthly Data Table */}
            <div style={{
              background: C.card, borderRadius: 16, padding: '22px 24px',
              border: `1px solid ${C.border}`, maxHeight: 440, overflowY: 'auto',
            }}>
              <h3 style={{ fontSize: 15, fontWeight: 600, margin: '0 0 12px', color: C.charcoalDeep }}>
                Monthly Data
              </h3>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 11 }}>
                <thead>
                  <tr style={{ borderBottom: `2px solid ${C.border}` }}>
                    <th style={{ padding: '6px 8px', textAlign: 'left', color: C.stone, fontWeight: 600 }}>Month</th>
                    <th style={{ padding: '6px 8px', textAlign: 'right', color: C.stone, fontWeight: 600 }}>Score</th>
                    <th style={{ padding: '6px 8px', textAlign: 'right', color: C.plum, fontWeight: 600 }}>GT</th>
                    <th style={{ padding: '6px 8px', textAlign: 'right', color: C.coral, fontWeight: 600 }}>BA Rank</th>
                    <th style={{ padding: '6px 8px', textAlign: 'right', color: C.sage, fontWeight: 600 }}>Reddit</th>
                    <th style={{ padding: '6px 8px', textAlign: 'center', color: C.stone, fontWeight: 600 }}>Status</th>
                  </tr>
                </thead>
                <tbody>
                  {current.monthly_scores.map((ms, i) => {
                    const isDetection = current.detection_date && ms.month === current.detection_date;
                    const isExploding = ms.total >= 60;
                    return (
                      <tr key={i} style={{
                        borderBottom: `1px solid ${C.borderLight}`,
                        background: isDetection ? C.sageLight : isExploding ? C.coralLight + '44' : 'transparent',
                      }}>
                        <td style={{ padding: '5px 8px', fontFamily: "'JetBrains Mono', monospace", color: C.ink }}>
                          {ms.month.slice(0, 7)}
                        </td>
                        <td style={{
                          padding: '5px 8px', textAlign: 'right', fontWeight: 700,
                          fontFamily: "'JetBrains Mono', monospace",
                          color: ms.total >= 60 ? C.coral : ms.total >= 40 ? C.sage : C.stone,
                        }}>
                          {ms.total.toFixed(1)}
                        </td>
                        <td style={{ padding: '5px 8px', textAlign: 'right', fontFamily: "'JetBrains Mono', monospace", color: C.plum }}>
                          {ms.gt_value || '—'}
                        </td>
                        <td style={{ padding: '5px 8px', textAlign: 'right', fontFamily: "'JetBrains Mono', monospace", color: C.coral }}>
                          {ms.ba_rank || '—'}
                        </td>
                        <td style={{ padding: '5px 8px', textAlign: 'right', fontFamily: "'JetBrains Mono', monospace", color: C.sage }}>
                          {ms.reddit_posts || '—'}
                        </td>
                        <td style={{ padding: '5px 8px', textAlign: 'center' }}>
                          {isExploding ? (
                            <span style={{ padding: '2px 8px', borderRadius: 10, fontSize: 9, fontWeight: 700, background: C.coralLight, color: C.coral }}>🔥 EXPLODING</span>
                          ) : ms.total >= 40 ? (
                            <span style={{ padding: '2px 8px', borderRadius: 10, fontSize: 9, fontWeight: 700, background: C.sageLight, color: C.sage }}>🌱 emerging</span>
                          ) : (
                            <span style={{ padding: '2px 8px', borderRadius: 10, fontSize: 9, fontWeight: 700, background: C.borderLight, color: C.sand }}>signal</span>
                          )}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>
        </>
      )}
    </div>
  );
}
